meta_product_name: "My invest"
meta_title: "My Invest - Centralisez tous vos investissements dans une seule et même application. "
meta_description: "My Invest est une web application qui permet d’avoir un aperçu en temps réel de ses investissements.
 Il permet de connecter un grand nombre de portefeuilles crypto sur la plateforme ainsi que vos investissements dansl'immobilier, vos comptes bancaires, vos crédits et vos investissements custom."
meta_image: "MI_facebook_opengraph"
twitter_account: "@my_invest_twitter_account"
